### ISSUE TITLE
java -jar issue: constructing graphs without -f parameter leads to an error

### ISSUE THREAD

**Issue by seebi** [spice-h2020/sparql.anything#12]
small issue: the help says TTL is the default but without `-f TTL` I get this exception:

```
Exception in thread "main" org.apache.jena.riot.RiotException: No graph writer for 'Lang:RDF/XML'
```

**Comment by luigi-asprino** [comment]
Hi @seebi,
Thanks for reporting this issue, it has been fixed in version 0.0.3.
Luigi
