### ISSUE TITLE
Add default type for root element

### ISSUE THREAD

**Issue by enridaga** [spice-h2020/sparql.anything#5]
It would be useful to be able to distinguish root elements from normal containers.

What about adding, for example `rdf:type <urn:facade-x:default#root>`?

**Comment by enridaga** [comment]
This would change the example on the front page as:

```
@prefix fx: <urn:facade-x:ns#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
[] rdf:type fx:Root ;
    rdf:_1 [
      fx:someKey "some value" ;
      rdf:_1 "another value with unspecified key" ;
      rdf:_2 [
        rdf:type fx:MyType
        rdf:_1 "another value" 
    ]
```

**Comment by enridaga** [comment]
Harder for the JSONTransformer as it delegates to json2rdf - maybe we can transfer the main code inside sparql.anything? This will make it easier to evolve it with the rest of the framework.

**Comment by enridaga** [comment]
I think JSON is the only one missing now.

**Comment by luigi-asprino** [comment]
Commit 17e049d closes this issue
